In [1]:
from ultralytics import YOLO
import cv2
import torch

# Load a model
model = YOLO("yolo11n-pose.pt")

In [3]:
# Open the video file
video_path = "sample_back.mp4"
cap = cv2.VideoCapture(video_path)

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLO inference on the frame
        results = model(frame)

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Display the annotated frame
        cv2.imshow("YOLO Inference", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()

0: 640x384 1 person, 52.7ms
Speed: 2.8ms preprocess, 52.7ms inference, 0.7ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 45.8ms
Speed: 1.8ms preprocess, 45.8ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 40.2ms
Speed: 1.4ms preprocess, 40.2ms inference, 0.7ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 46.1ms
Speed: 1.3ms preprocess, 46.1ms inference, 0.8ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 48.6ms
Speed: 1.3ms preprocess, 48.6ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 48.5ms
Speed: 1.6ms preprocess, 48.5ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 45.5ms
Speed: 1.5ms preprocess, 45.5ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 47.5ms
Speed: 1.6ms preprocess, 47.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640

In [4]:
results

[ultralytics.engine.results.Results object with attributes:
 
 boxes: ultralytics.engine.results.Boxes object
 keypoints: ultralytics.engine.results.Keypoints object
 masks: None
 names: {0: 'person'}
 obb: None
 orig_img: array([[[214, 206, 196],
         [214, 206, 196],
         [214, 206, 196],
         ...,
         [118, 117, 119],
         [118, 117, 119],
         [117, 116, 118]],
 
        [[216, 208, 198],
         [216, 208, 198],
         [216, 208, 198],
         ...,
         [118, 117, 119],
         [118, 117, 119],
         [118, 117, 119]],
 
        [[218, 210, 200],
         [218, 210, 200],
         [217, 209, 199],
         ...,
         [119, 118, 120],
         [118, 117, 119],
         [118, 117, 119]],
 
        ...,
 
        [[  7,  12,  10],
         [ 33,  38,  36],
         [ 77,  82,  80],
         ...,
         [140, 143, 143],
         [140, 143, 143],
         [140, 143, 143]],
 
        [[  5,  10,   8],
         [ 36,  41,  39],
         [ 82,  87,

In [5]:
results[0].keypoints.data

tensor([[[0.0000e+00, 0.0000e+00, 3.4915e-02],
         [0.0000e+00, 0.0000e+00, 1.6761e-02],
         [0.0000e+00, 0.0000e+00, 7.2402e-03],
         [3.3545e+02, 4.7740e+02, 8.3652e-01],
         [4.1490e+02, 4.7882e+02, 5.5362e-01],
         [3.0509e+02, 5.3476e+02, 9.9381e-01],
         [4.4061e+02, 5.4338e+02, 9.9419e-01],
         [2.6785e+02, 4.2570e+02, 9.7665e-01],
         [4.7844e+02, 4.4143e+02, 9.6938e-01],
         [2.8977e+02, 3.3329e+02, 9.1484e-01],
         [4.6341e+02, 3.4485e+02, 8.8362e-01],
         [3.2842e+02, 7.8918e+02, 9.9980e-01],
         [4.1219e+02, 7.9350e+02, 9.9979e-01],
         [3.4533e+02, 9.7396e+02, 9.9814e-01],
         [4.0568e+02, 9.8018e+02, 9.9813e-01],
         [3.5597e+02, 1.1623e+03, 9.7486e-01],
         [4.0526e+02, 1.1645e+03, 9.7606e-01]]])

In [6]:
keypoints = torch.tensor(results[0].keypoints.xy)
keypoints[0]

C:\Users\Roydon\AppData\Local\Temp\ipykernel_29656\3445061273.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  keypoints = torch.tensor(results[0].keypoints.xy)


tensor([[   0.0000,    0.0000],
        [   0.0000,    0.0000],
        [   0.0000,    0.0000],
        [ 335.4501,  477.4008],
        [ 414.9041,  478.8189],
        [ 305.0924,  534.7606],
        [ 440.6088,  543.3785],
        [ 267.8514,  425.6990],
        [ 478.4362,  441.4295],
        [ 289.7686,  333.2870],
        [ 463.4120,  344.8450],
        [ 328.4186,  789.1836],
        [ 412.1949,  793.4993],
        [ 345.3286,  973.9587],
        [ 405.6785,  980.1802],
        [ 355.9671, 1162.3225],
        [ 405.2606, 1164.5421]])

In [7]:
left_shoulder = keypoints[0,5]
right_shoulder = keypoints[0,6]
left_ankle = keypoints[0,15]
right_ankle = keypoints[0,16]

In [8]:
right_ankle

tensor([ 405.2606, 1164.5421])